name: flagger
author: Wilker LÃºcio <wilkerlucio@gmail.com>
version: 0.2.0
homepage: https://github.com/wilkerlucio/dart-flagger
description: Flag mixins for object annotation
dev_dependencies:
  barrier: '>0.0.1'
